notifications:
  email: false

language: node_js

node_js:
  - "8.11.1"

sudo: false

branches:
  only:
  - master

if: tag IS blank

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --frozen-lockfile

cache:
  yarn: true
  directories:
    - ".cache"
    - ".eslintcache"
    - "node_modules"

script:
  - yarn prettier --list-different
  - yarn lint
  - yarn jest --maxWorkers=4

after_success:
  - yarn codecov

deploy:
  provider: script
  script: curl -X POST -d '{}' $NETLIFY_DEPLOY_WEBHOOK && yarn semantic-release
  skip_cleanup: true
  on:
    branch: master
