notifications:
  email: false

language: node_js

node_js:
  - 'lts/dubnium'

sudo: false

branches:
  only:
    - master
    - v16

if: tag IS blank

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - python --version
  - git --version

install:
  - yarn install --frozen-lockfile
  - pip install --user -r requirements.txt

cache:
  yarn: true
  directories:
    - '.cache'
    - '.eslintcache'
    - 'node_modules'

script:
  - yarn lint
  - yarn test-schema
  - yarn build
  - yarn jest --maxWorkers=4
  - yarn test-e2e

deploy:
  provider: script
  script: curl -X POST -d '{}' $NETLIFY_DEPLOY_WEBHOOK && yarn semantic-release
  skip_cleanup: true
  on:
    branch: master
