blank_issues_enabled: false
contact_links:
  - name: Renovate bot config help
    url: https://github.com/renovatebot/renovate/discussions
    about: Please ask questions on how to configure your Renovate bot here.
