name: auto-pr

on:
  pull_request_target:
    types:
      - opened

jobs:
  review:
    if: github.event.action == 'opened' && !endsWith(github.event.pull_request.user.login, '[bot]')
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
      - uses: hkusu/review-assign-action@5bee595fdb9765d4a0bd35724b6302fa15569158 # v1.4.0
        with:
          reviewers: ${{ vars.REVIEWERS }}
          max-num-of-reviewers: 2
