name: Close answered discussions

permissions:
  discussions: write

on:
  # run daily
  schedule:
    - cron: '0 0 * * *'

  # allow manual trigger
  workflow_dispatch:

jobs:
  close-answered-discussions:
    runs-on: ubuntu-latest
    if: github.repository == 'renovatebot/renovate'

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          show-progress: false

      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const script = require('.github/workflows/close-answered-discussions/script.js')
            console.log(await script({github, context, discussionAnsweredDays: 30}))
