name: 'Compile Mermaid Markdown into Image'

on:
  push:
    paths:
      - '**/docs/development/assets/*.md'
jobs:
  build:
    runs-on: ubuntu-latest5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e '.*\.md$' -e '.*\.mermaid$' | xargs)"

      - name: mermaid files changed
        run: |
          echo ${{ steps.getfile.outputs.files }}

      - name: compile mermaid
        uses: neenjaw/compile-mermaid-markdown-action@0.3.3
        with:
          files: ${{ steps.getfile.outputs.files }}
          output: 'mermaidOutput'
        env:
          HIDE_CODEBLOCKS: 1
          ABSOLUTE_IMAGE_LINKS: 1
          OUTPUT_FILE_TYPE: 'svg'

      - name: show changes
        run: |
          git status

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add compiled mermaid
          title: '[MMDC] New mermaid files compiled'
          body: |
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: report, automated pr

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
