name: trivy

on:
  # schedule:
  #   - cron: '59 11 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    strategy:
      matrix:
        tag:
          - latest
          - full

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          show-progress: false

      - uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          image-ref: ghcr.io/renovatebot/renovate:${{ matrix.tag }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - uses: github/codeql-action/upload-sarif@014f16e7ab1402f30e7c3329d33797e7948572db # v4.31.3
        with:
          sarif_file: trivy-results.sarif
          category: 'docker-image-${{ matrix.tag }}'
