name: 'Update static data'
on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
  workflow_dispatch:

env:
  NODE_VERSION: 18

permissions:
  contents: write
  pull-requests: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Enable corepack
        shell: bash
        run: corepack enable

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Update static data
        run: pnpm run update-static-data

      - name: Run Prettier
        run: pnpm prettier-fix

      - name: Create pull request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          author: 'Renovate Bot <renovate@whitesourcesoftware.com>'
          branch: 'chore/update-static-data'
          commit-message: 'fix(data): automatic update of static data'
          committer: 'Renovate Bot <renovate@whitesourcesoftware.com>'
          title: 'fix(data): automatic update of static data'
          assignees: rarkins,viceice
