name: 'Update static data'
on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
  workflow_dispatch:

env:
  NODE_VERSION: 16

permissions:
  contents: write
  pull-requests: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Update static data
        run: yarn run update-static-data

      - name: Run Prettier
        run: yarn prettier-fix

      - name: Create pull request
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04 # v4.2.3
        with:
          author: 'Renovate Bot <renovate@whitesourcesoftware.com>'
          branch: 'chore/update-static-data'
          commit-message: 'fix(data): automatic update of static data'
          committer: 'Renovate Bot <renovate@whitesourcesoftware.com>'
          title: 'fix(data): automatic update of static data'
          assignees: rarkins,viceice
